// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQNvlV73WxQyo4MEnVWFSQ6Vo8ZpTJMZA',
    appId: '1:1004178093819:android:5391d374f771a89f07625e',
    messagingSenderId: '1004178093819',
    projectId: 'literature-board-game',
    storageBucket: 'literature-board-game.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAK1_xMcYO2YeAZarQFacRtjeY3i_ow2Zg',
    appId: '1:1004178093819:ios:d5e1a79efb2c798f07625e',
    messagingSenderId: '1004178093819',
    projectId: 'literature-board-game',
    storageBucket: 'literature-board-game.firebasestorage.app',
    iosBundleId: 'com.example.literatureBoardGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBzA8ZTmJZJRK5u5hFSVtRVPumiPpV3Ngg',
    appId: '1:1004178093819:web:4d29fc7e1a83328507625e',
    messagingSenderId: '1004178093819',
    projectId: 'literature-board-game',
    authDomain: 'literature-board-game.firebaseapp.com',
    storageBucket: 'literature-board-game.firebasestorage.app',
    measurementId: 'G-7S86GX63DE',
  );
}
